export type ColorToken =
  | "color-text-primary"
  | "color-text-secondary"
  | "color-text-inverse"
  | "color-background-primary"
  | "color-background-secondary"
  | "color-background-inverse"
  | "color-border-default"
  | "color-border-strong"
  | "color-action-primary"
  | "color-action-primary-hover"
  | "color-feedback-success"
  | "color-feedback-error"
  | "radius-sm"
  | "radius-md"
  | "radius-lg"
  | "radius-xl"
  | "radius-pill"
